### ISSUE TITLE
Hi, how do you cope with errors when bunyan writes to process.stdout?

### ISSUE THREAD

**Issue by AVVS** [lancespeelmon/gooder-bunyan#1]
usually it ends up with smth like in case I use `stream-stdout`, if it's `process.stdout` or `process.stderr` I just get illegal invocation and process crash right away

```
{"name":"rfx-api","hostname":"Vitalys-iMac.local","pid":45291,"level":30,"event":"log","data":{"event":"log","timestamp":1466697579710,"tags":["info"],"data":"Adding a new policy called isAdmin","pid":45291},"msg":"","time":"2016-06-23T15:59:39.711Z","src":{"file":"/Users/vitaly/projects/rfx-api/node_modules/gooder-bunyan/lib/index.js","line":55,"func":"GoodBunyan._write"},"v":0}

/Users/vitaly/projects/rfx-api/node_modules/readable-stream/lib/_stream_writable.js:366
  cb();
  ^
TypeError: cb is not a function
    at afterWrite (/Users/vitaly/projects/rfx-api/node_modules/readable-stream/lib/_stream_writable.js:366:3)
    at _combinedTickCallback (internal/process/next_tick.js:80:20)
    at process._tickCallback (internal/process/next_tick.js:98:9)
---------------------------------------------
    at onwrite (/Users/vitaly/projects/rfx-api/node_modules/readable-stream/lib/_stream_writable.js:355:7)
    at WritableState.onwrite (/Users/vitaly/projects/rfx-api/node_modules/readable-stream/lib/_stream_writable.js:122:5)
    at module.exports.onwrite (/Users/vitaly/projects/rfx-api/node_modules/stdout-stream/index.js:30:47)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:741:5)
```

**Comment by AVVS** [comment]
Was able to patch it, but I have no idea why this happened, solution seems retarded:

https://github.com/trentm/node-bunyan/issues/384#issuecomment-228111971

**Comment by lancespeelmon** [comment]
I am sorry I don't have a good answer... I have bunyan logging directly to a logstash listener so I have not run across that problem.
